export const getEducation  = async () => {
    try{

    } catch(error){
        
    }
}